apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    run: svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
