name: Daily Ci
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: 0 8 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - uses: xhyrom/setup-bun@v0.1.7
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: bun i
      - run: npx nx-cloud start-ci-run
      - run: bun nx run-many --parallel --max-parallel=5 --all --skip-nx-cache --target=lint
#      - run: bun nx run-many --parallel --max-parallel=5 --all --skip-nx-cache --target=test
      - run: bun nx run-many --parallel --max-parallel=5 --all --skip-nx-cache --target=build --prod
#      - run: bun nx run-many --parallel --max-parallel=5 --all --skip-nx-cache --target=e2e
      - name: Stop agents
        run: npx nx-cloud stop-all-agents
        if: ${{ always() }}

  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 20
    strategy:
      matrix:
        agent: [ 1, 2, 3 ]
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: xhyrom/setup-bun@v0.1.7
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: bun i
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
