name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_BUILDKIT: 1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: xhyrom/setup-bun@v0.1.7
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: bun i
      - run: bun nx affected --target=build --parallel --max-parallel=2 --prod
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: xhyrom/setup-bun@v0.1.7
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: bun i
#      - run: bun nx affected --target=test --parallel --max-parallel=2
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: xhyrom/setup-bun@v0.1.7
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: bun i
      - run: bun nx affected --target=lint --parallel --max-parallel=2

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: xhyrom/setup-bun@v0.1.7
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: bun i
#      - run: bun nx affected --target=e2e --parallel --max-parallel=2
  docker:
    runs-on: ubuntu-latest
#    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: xhyrom/setup-bun@v0.1.7
        with:
          bun-version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: bun i
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Docker Buildx builders
        run: docker buildx ls
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: |-
          gcloud --quiet auth configure-docker europe-west1-docker.pkg.dev
#      - run: docker run --privileged --rm tonistiigi/binfmt --install all
#      - run: docker buildx create --use
      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - run: bun nx affected --target=build --parallel --max-parallel=2 --prod
      - name: Build docker images
        run: bun nx affected --target=docker --parallel --max-parallel=1
        env:
          TAG: ${{ steps.vars.outputs.sha_short }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NX_VERBOSE_LOGGING: true

